### ISSUE TITLE
directory not supported

### ISSUE THREAD

**Issue by ghost** [JamesBoer/Heady#1]
directory listing not supported?
https://i.imgur.com/DlyFIQc.png about this.

**Comment by JamesBoer** [comment]
I'm trying to understand the issue you're having, or the feature you'd like to see.  Could you perhaps clarify for me?

**Comment by ghost** [comment]
@JamesBoer recursive find .c/.h files

**Comment by JamesBoer** [comment]
-r or --recursive is supposed to do that.  Is it not working correctly?

**Comment by ghost** [comment]
@JamesBoer i am not testes -r option. It is not needed at this point.

**Comment by JamesBoer** [comment]
If you pass in a source path with -s or --source, it's supposed to scan all files in the given directory.  You can exclude specific files if you need to.  Is this what you mean?

**Comment by ghost** [comment]
Yes
